import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from './components/Header/Header'
import Footer from './components/Footer/Footer'
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Head from "next/head";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "../../context/AuthContext";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Suspense fallback={<div className="text-center text-2xl">Loading...</div>}>
          <AuthProvider>
            <Header />
            <Toaster position="top-right" reverseOrder={false} />
            {children}
            <Footer />
          </AuthProvider>
        </Suspense>
      </body>
    </html>
  );
}
