import React from "react";
import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { Suspense } from "react";
import "@/app/globals.css";
import { ThemeProvider } from "./components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Adminlayout({ children}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="admin-layout">
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <Suspense
          fallback={<div className="text-center text-2xl">Loading...</div>}  >
          <Toaster position="top-right" reverseOrder={false} />
          {children}
        </Suspense>
      </ThemeProvider>
    </div>
  );
}
